version: '3'
services:

#  abcd:
#    build: .
#    restart: always
#    environment:
#      - FLASK_ENV=development
#      - SECRET_KEY
#      - MONGODB_DB=${DB}
#      - MONGODB_HOST=mongo
#      - MONGODB_PORT=27017
#      - MONGODB_USERNAME=${DB_USER}
#      - MONGODB_PASSWORD=${DB_PASS}
#    ports:
#      - 8080:5000
#    depends_on:
#      - mongo
#    volumes:
#      - .:/usr/src/app/

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    ports:
      - 27017:27017  # opening port for development only!
    volumes:
      - ./datadir:/data/db

  mongo-express:  # mongo-express only for development only!
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASS}
    depends_on:
      - mongo