[tool.poetry]
name = "abcd"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
notebook = "^6.5.4"
numpy = "^1.24.3"
tqdm = "^4.65.0"
pymongo = "^4.3.3"
matplotlib = "^3.7.1"
ase = "^3.22.1"
lark = "^1.1.5"

[tool.poetry.group.dev.dependencies]
mongomock = "^4.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."console_scripts"]
"abcd" = "abcd.frontends.commandline:main"
